version: 2.1

executors:
  cpp-executor:
    docker:
      - image: circleci/cpp:latest
    working_directory: ~/tech-template

jobs:
  test:
    executor: cpp-executor
    steps:
      # Step to authenticate Docker Hub credentials
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y cmake g++ ninja-build
      - run:
          name: Build Project
          command: |
            mkdir build
            cd build
            cmake .. -G Ninja
            ninja
      - run:
          name: Run Unit Tests
          command: |
            cd build
            ctest --output-on-failure
      - store_test_results:
          path: build/Testing/Temporary
      - store_artifacts:
          path: build/Testing/Temporary

workflows:
  version: 2
  test:
    jobs:
      - test
