version: 2.1

executors:
  cpp-executor:
    machine:
      image: ubuntu-2204:current  # Use a machine executor with Docker support
    working_directory: ~/tech-template

jobs:
  test:
    executor: cpp-executor
    steps:
      # Authenticate Docker Hub (Uncomment if needed)
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin || echo "Docker login failed, continuing..."

      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y cmake g++ ninja-build

      - name: Build and Install GTest
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib
          sudo cp -r /usr/src/googletest/googletest/include/gtest /usr/include/

      - run:
          name: Build Project
          command: |
            mkdir -p build/test_results  # Ensure test results directory exists
            cd build
            cmake .. -G Ninja
            ninja

      - run:
          name: Run Unit Tests and Store Results
          command: |
            cd build
            ctest --output-on-failure | tee test_results/ctest_output.log
            cp -r Testing/Temporary test_results/ 2>/dev/null || echo "No test output directory found."

      - store_test_results:
          path: build/test_results  # Store structured test results

      - store_artifacts:
          path: build/test_results  # Store test logs as artifacts

workflows:
  version: 2
  test:
    jobs:
      - test
