version: 2.1

jobs:
  test:
    # No executor specified, so it runs directly on the VM
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update  # Or your system's package manager
            sudo apt install -y cmake g++ ninja-build # Add other dependencies
            # ... any other dependencies you need (libraries, etc.)
      - run:
          name: Build Project
          command: |
            mkdir build
            cd build
            cmake .. -G Ninja
            ninja
      - run:
          name: Run Unit Tests
          command: |
            cd build
            ctest --output-on-failure
      - store_test_results:
          path: build/Testing/Temporary
      - store_artifacts:
          path: build/Testing/Temporary

workflows:
  version: 2
  test:
    jobs:
      - test