version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current  # Use the latest Ubuntu machine executor
    working_directory: ~/tech-template
    steps:
      - checkout  # Checkout repo first!

      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y cmake g++ ninja-build libgtest-dev
            cd /usr/src/googletest
            sudo cmake CMakeLists.txt
            sudo make
            sudo cp lib/*.a /usr/lib
            sudo cp -r googletest/include/gtest /usr/include/

      - run:
          name: Configure and Build
          command: |
            mkdir -p build/test_results
            cd build
            cmake .. -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            ninja

      - run:
          name: Run Unit Tests
          command: |
            cd build
            ctest --output-on-failure | tee test_results/ctest_output.log
            cp -r Testing/Temporary test_results/ 2>/dev/null || echo "No test output directory found."

      - store_test_results:
          path: build/test_results  # Store structured test results

      - store_artifacts:
          path: build/test_results  # Store test logs as artifacts

workflows:
  version: 2
  test:
    jobs:
      - test
